name: CI

on:
  workflow_dispatch:

# ✅ allow pushing images to GHCR with the GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ghcr requires lowercase image path (owner/repo)
      - name: Lowercase repo
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # image name: ghcr.io/<owner>/<repo>:<sha>
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          # optional but reduces metadata/provenance issues
          provenance: false
